# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "D:/keith_temp/quartusII/DE1_QIIv71/DE1_demonstrations/DE1_SD_Card_Audio/DE1_SD_Card_Audio.qpf"
project_close